name: Release CertGen Docker Image
on:
  workflow_dispatch: # manual trigger only
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Generate datetime tag
        id: tag
        run: |
          TAG="$(date -u +'%Y%m%d')"
          echo "Generated tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: thecuriousgeek/CertificateGenerator
          token: ${{ secrets.GH_PAT }}
          path: release-tmp
      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./cert-gen.html
          git commit -m "Update readme.md"
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: release-tmp
          push: true
          tags: |
            ghcr.io/thecuriousgeek/cert-gen:latest
            ghcr.io/thecuriousgeek/cert-gen:${{ env.TAG }}
      - name: Copy readme
        run: cp release-tmp/README.md ./cert-gen.html         
